services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sgala-sqlserver
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Sg4l@_Srv#2024_Kp7xQ"
      TZ: "America/Mexico_City"
    ports:
      - "1433:1433"
    volumes:
      - sql_datos:/var/opt/mssql
      - ./init.sql:/usr/src/init.sql
      - ./entrypoint.sh:/usr/src/entrypoint.sh
    command: ["/bin/bash", "/usr/src/entrypoint.sh"]
    restart: unless-stopped

volumes:
  sql_datos:
